version: "3.9"
services:
  nginx:
    image: nginx:latest
    restart: always
    volumes:
    - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
    - "8000:80"
  serverone:
    image: nuttawut503/mydocker:1.0
    environment:
    - name=Ant
  servertwo:
    image: nuttawut503/mydocker:1.0
    environment:
    - name=Bird
  serverthree:
    image: nuttawut503/mydocker:1.0
    environment:
    - name=Cat
